"""urls table

Revision ID: 5bfe8d25ed3c
Revises: 
Create Date: 2019-11-18 17:53:45.520283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bfe8d25ed3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('longurl', sa.String(length=1024), nullable=True),
    sa.Column('shorturl', sa.String(length=24), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urls_longurl'), 'urls', ['longurl'], unique=True)
    op.create_index(op.f('ix_urls_shorturl'), 'urls', ['shorturl'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_shorturl'), table_name='urls')
    op.drop_index(op.f('ix_urls_longurl'), table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###
